Drop support for Python 2.*
Collecting scipy==0.17.1 (from -r etc/requirements.txt (line 25))
...
RuntimeError: Python version >= 3.5 required

https://travis-ci.org/adegtyarev/docker-zipline/jobs/556150585